# Generated by Django 5.1.5 on 2025-01-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_word_user_alter_word_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictapp.word')),
            ],
            options={
                'verbose_name': 'Word User Relationship',
                'verbose_name_plural': 'Word User Relationships',
                'ordering': ['-created_at'],
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='users',
            field=models.ManyToManyField(related_name='word_collection', through='dictapp.WordUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
    ]
